// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwGTViyDTVBLCwjwU9_ldHxM6PptXWOq4',
    appId: '1:586446588869:web:9d90a298ecb274914259ac',
    messagingSenderId: '586446588869',
    projectId: 'creative-engineering-exercise',
    authDomain: 'creative-engineering-exercise.firebaseapp.com',
    storageBucket: 'creative-engineering-exercise.appspot.com',
    measurementId: 'G-9XSYJZWQET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABfGDmN7_VSV16mgYPQeaI6uHLdBYPbpY',
    appId: '1:586446588869:ios:ee59f1acc23eb3314259ac',
    messagingSenderId: '586446588869',
    projectId: 'creative-engineering-exercise',
    storageBucket: 'creative-engineering-exercise.appspot.com',
    iosClientId: '586446588869-sbrm5t0r063ben4pii3e435r7kljmial.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABfGDmN7_VSV16mgYPQeaI6uHLdBYPbpY',
    appId: '1:586446588869:ios:ee59f1acc23eb3314259ac',
    messagingSenderId: '586446588869',
    projectId: 'creative-engineering-exercise',
    storageBucket: 'creative-engineering-exercise.appspot.com',
    iosClientId: '586446588869-sbrm5t0r063ben4pii3e435r7kljmial.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwGTViyDTVBLCwjwU9_ldHxM6PptXWOq4',
    appId: '1:586446588869:web:a79da69594b87fe24259ac',
    messagingSenderId: '586446588869',
    projectId: 'creative-engineering-exercise',
    authDomain: 'creative-engineering-exercise.firebaseapp.com',
    storageBucket: 'creative-engineering-exercise.appspot.com',
    measurementId: 'G-WPZGQXCR0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrUJpBnj5OevzHIdkJxGil4cIns28-69U',
    appId: '1:586446588869:android:1beea976b31ade464259ac',
    messagingSenderId: '586446588869',
    projectId: 'creative-engineering-exercise',
    storageBucket: 'creative-engineering-exercise.appspot.com',
  );

}